@EventHub.Api_HostAddress = http://localhost:5213

GET {{EventHub.Api_HostAddress}}/ping/
Accept: application/json

###

GET {{EventHub.Api_HostAddress}}/event

###

GET {{EventHub.Api_HostAddress}}/groupEventsByMonth

###

GET {{EventHub.Api_HostAddress}}/fewSeats

###

GET {{EventHub.Api_HostAddress}}/paginated

